token:
  - "MTM4Nzg4NjA4NzMwNDc3Mzg5OA.GE3za7.cIbsdZDX4qIKyKaPehawyJjK69cKJ8ZA7jW2Ls"
  - "your_token_2"
channel_id:
  - "1491198046103666793"
  - "channel_id_2"
  - "channel_id_3"
token_delay: 5  # Delay for each token processing in seconds
message_delay: 2  # Delay for each message sent in seconds
restart_delay: 10  # Delay before restarting the bot in seconds
send_mode: "random"  # Options: "random" or "bulk"
